#ifndef DB_CONSUMER_H
#define DB_CONSUMER_H
#include "Provider.h"

//TODO: this needs to be tested
/**
 * This is the consumer class that will be utilized to consume the records generated by the Provider class
 */
class Consumer {
public:
    // the source that will generate records
    Provider source;

    // the consumer constructor
    Consumer(Provider givenSource);

    // continues to get new records until a null record has been reached
    void consume();
};


#endif //DB_CONSUMER_H
