#pragma once

#include <memory>

#include "Provider.h"
#include "Record.h"

using namespace std;

/**
 * This is the consumer class that will be utilized to consume the records generated by the Provider class
 */
class Consumer {
public:
    // the consumer constructor
    Consumer(shared_ptr<Provider> _source): source(_source) {}

    // continues to get new records until a null record has been reached
    void consume() {
        while (true) {
            shared_ptr <Record> ptr = source->next();
            // if null ptr then end consuming
            if (!ptr) {
                return;
            }
        }
    }

private:
    shared_ptr<Provider> source; // the source that will generate records
};
