#pragma once

#include <memory>

#include "Provider.h"
#include "Record.h"
#include "IODevice.h"

using namespace std;

/**
 * This is the consumer class that will be utilized to consume the records generated by the Provider class
 */
class Consumer {
public:
    virtual ~Consumer() {}

    // continues to get new records until a null record has been reached
    virtual void consume() = 0;
};

class NoopConsumer : public Consumer {
public:
    NoopConsumer(shared_ptr<Provider> _source): source(_source) {}

    void consume() override {
        while(true) {
            shared_ptr<Record> ptr = source->next();
            if(ptr == nullptr) return;
        }
    }

private:
    shared_ptr<Provider> source; // the source that will generate records
};



class DeviceConsumer : public Consumer {
public:
    DeviceConsumer(shared_ptr<Provider> _source, shared_ptr<IODevice> _device, int _bufferSize);
    void consume() override;

private:
    void doWrite();
    void appendRecord(shared_ptr<Record> &ptr);
    shared_ptr<Provider> source;               // the source that will generate records
    shared_ptr<IODevice> outputDevice;         // the output device where the records will be written
    uint64_t deviceOffset;                     // the location where the next buffer should be written
    unique_ptr<uint8_t[]> buffer;              // a smallish buffer to stage data so we don,t make so many os calls
    int bufferSize;                            // the size of the buffer
    int bufferOffset;                          // the offset into the buffer which has already been filled
 };
