#ifndef CONVERT_H
#define CONVERT_H

#include <charconv>
#include <cstring>
#include <iostream>
#include <sstream>
#include <type_traits> // For std::is_integral

// generated by my good friend, ChatGpt
template<typename IntegerType, typename std::enable_if<std::is_integral<IntegerType>::value, bool>::type = true>
bool parseInteger(const char* str, IntegerType& outValue) {
    std::from_chars_result result = std::from_chars(str, str + std::strlen(str), outValue);

    if (result.ec == std::errc::invalid_argument) {
        std::cerr << "Error: Invalid argument." << std::endl;
        return false;
    } else if (result.ec == std::errc::result_out_of_range) {
        std::cerr << "Error: Result out of range." << std::endl;
        return false;
    } else if (result.ptr != str + std::strlen(str)) {
        // Not all characters were consumed, indicating some invalid input.
        std::cerr << "Error: Entire string not converted." << std::endl;
        return false;
    }

    // Success
    return true;
}

template<typename T>
bool parseFloatingPoint(const std::string& str, T& value) {
    static_assert(std::is_floating_point<T>::value, "T must be a floating point type");

    std::istringstream iss(str);
    iss >> value;

    // Check if the entire string was consumed and if the read was successful
    return iss.eof() && !iss.fail();
}

#endif // CONVERT_H